title = "My New Hugo Site"
baseURL = ""
languageCode = "en-us"
theme = "ananke"
resourceDir = "./resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "ACCOMMIDATION"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/accommodation/"
    weight = -100

  [[menu.main]]
    identifier = "about"
    name = "CONTACT"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110


[languages]
  [languages.en]
    title = "QIAN DENG HOTEL"
    weight = 1
    contentDir = "content/en"
  [languages.zh]
    title = "千灯酒店"
    weight = 2
    contentDir = "content/zh"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/images/logo.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  featured_image = "/images/huayuan.jpg"
  recent_posts_number = 2
  mainSections = ["accommodation"]
  recent_copy = "ACCOUMENTS"
